export const Posts = [
  {
    id: 1,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 6,
  },
  {
    id: 2,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 6,
  },
  {
    id: 3,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 3,
    like: 32,
    comment: 6,
  },
  {
    id: 4,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 6,
  },
  {
    id: 5,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 6,
  },
  {
    id: 6,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 6,
    like: 32,
    comment: 6,
  },
  {
    id: 7,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 7,
    like: 32,
    comment: 6,
  },
  {
    id: 8,
    desc: "THis is the New POst",
    photo: `${require("../../images/Profiles/Hanako.jpeg")}`,
    date: "5 mins ago",
    userId: 8,
    like: 32,
    comment: 6,
  },
];
